version: '3.7' 
services: 
  python-flask-app-container:
    image: billing_server:1.0
    container_name: python-flask-app-container
    ports:
     - "${PORT_SERVER}:5000"
    volumes:
     - /app/git/Billing/app/in/rates.xlsx:/app/in/rates.xlsx
    networks:
     - mynet
  mysql-flask-app-container:
    image: mysql_db:1.0
    container_name: mysql-flask-app-container
    ports:
     - "${PORT_DB}:3306"
    volumes:
     - /app/git/Billing/db_volume:/var/lib/mysql
    networks:
     - mynet
    depends_on:
     - python-flask-app-container

networks:
  mynet:
    name: mynet
