version: '3.7' 
services: 
  billingappprod:
    image: "${VERSIONAPP}"
    container_name: "${NAME_APP}"
    ports:
     - "${PORT_SERVER}:5000"
    volumes:
     - /app/git/Billing/app/in:/app/in
    networks:
     - mynet
  mysqlbillingprod:
    image: "${VERSIONMYSQL}"
    container_name: "${NAME_DB}"
    ports:
     - "${PORT_DB}:3306"
    volumes:
     - /app/git/Billing/db_volume:/var/lib/mysql
    networks:
     - mynet
    depends_on:
     - billingappprod

networks:
  mynet:
    name: mynet
