version: "3.7"
services:
  WeightApp:
    container_name: "${NAME_APP}"
    image: "${VERSION}"
    build: /app/git/Weight/app-weight
    ports:
      - "${PORT_SERVER}:5000"
    networks:
      - mynet

  WeightMysql:
    container_name: "${NAME_DB}"
    image: mysql:latest
    ports:
      - "${PORT_DB}:3306"
    depends_on:
      - WeightApp
    networks:
      - mynet
    command: --init-file /data/application/init-test.sql
    volumes:
        - /app/git/Weight/database:/data/application
        - flask_app_volume_test:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: weight
      
volumes:
  flask_app_volume_test:
    name: flask_app_volume_test

networks:
  mynet:
    name: mynet
