version: "3.7"
services:
  app:
    container_name: flaskapp
    build: ./app-weight
    ports:
      - "6001:5000"
    networks:
      - "new_network"
      
  
  mydb:
    container_name: mysqlcont
    image: mysql:latest
    ports:
      - "6000:3306"
    depends_on:
      - app
    networks:
      - "new_network"
    command: --init-file /data/application/init.sql
    volumes:
        - ./database/weight.sql:/data/application/init.sql
        - flask_app_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: weight



networks: 
    new_network:
      name: new_network
volumes:
    flask_app_volume:
      name: flask_app_volume