version: "3.7"
services:
  WeightAppprod:
    container_name: "${NAME_APP}"
    image: "${VERSION}"
    build: /app/git/Weight/app-weight
    ports:
      - "${PORT_SERVER}:5000"
    networks:
      - mynet

  WeightMysqlprod:
    container_name: "${NAME_DB}"
    image: mysql:latest
    ports:
      - "${PORT_DB}:3306"
    depends_on:
      - WeightAppprod
    networks:
      - mynet
    volumes:
        - /app/git/Weight/database/init.sql:/data/application/init.d
        - flask_app_volume:/var/lib/mysql
    command: --init-file /data/application/init.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: weight
      
volumes:
  flask_app_volume:
    name: flask_app_volume

networks:
  mynet:
    name: mynet
